In [1]:
import os
import pandas as pd
import os
import pickle
import torch
import csv 

root = "D:/Desktop/code/6th-ABAW/dataset/"
feature = ["vit","wav2vec2"]
vid_path = os.path.join(root, feature[0])
aud_path = os.path.join(root, feature[1])



csv_path = os.path.join(root, 'train_split.csv')

df = pd.read_csv(csv_path)
print(len(df))
files_path = []
lens = []
for i in range(len(df)):
    filename = str(df.iloc[i,0]).zfill(5)
    # print(filename)
    vidfile_path = os.path.join(vid_path, filename+'.pkl')
    audfile_path = os.path.join(aud_path, filename+'.pkl')
    with open(vidfile_path, 'rb') as f:
        data = pickle.load(f)
        # print(type(data))
        print(data.dtype)
        len = data.shape[0]
        lens.append(len)
        break





8072
float32


c:\ProgramFiles\anaconda3\envs\MMSA\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [ ]:

file_name = str(csv_data.iloc[0, 0]).zfill(5) + '.pkl'
print(file_name)
file_path = os.path.join(root,feature[1],file_name)
print(file_path)
with open(file_path, 'rb') as f:
    data = pickle.load(f)
print(type(data), data.shape)
label = csv_data.iloc[0, 1:].to_numpy()
print(type(label),label.shape)

data_tensor = torch.tensor(data)
label_tensor = torch.tensor(label, dtype=torch.float32)
print(type(data_tensor), data_tensor.shape)
print(type(label_tensor),label_tensor.shape)

In [ ]:
import numpy as np

# 假设原始数据的 shape 是 [t, d]

# 创建原始数据
data = np.array([[1,2,3],[2,5,6],[3,8,9],[4,2,3],[5,2,3],[6,2,3],[7,2,3],[8,2,3],[9,2,3],[10,2,3]])

# 如果 t 小于 32，就将原始数据在时间维度上进行复制，直到 t 大于等于 32
if data.shape[0] < 6:
    data = np.pad(data, ((0, 6 - data.shape[0]), (0, 0)), mode='wrap')
    
# 在时间维度上等差的取出 32 个数据
else:
    indices = np.linspace(0, data.shape[0] - 1, num=6, dtype=int)
    data = data[indices]

print(data)
print(data.shape)


In [ ]:
import torch.nn as nn

import torch

x = torch.randn(4, 32, 128)

x = x.transpose(2, 1)
print(x.shape)

In [ ]:
from scipy import stats
import numpy as np

def calc_pearsons(preds, labels):
    r = stats.pearsonr(preds, labels)
    return r[0]

preds = np.array([np.random.rand() for i in range(10)])
labels = np.zeros(10)
preds, labels
calc_pearsons(preds, labels)

In [ ]:
import pandas as pd
df = pd.read_csv(r'D:\Desktop\code\6th-ABAW\dataset\valid_split.csv')
df

In [ ]:
for line in df.iloc:
    v = line[1:].values
    if v == np.zeros(6):
    break

In [ ]:
import numpy as np

data = np.load(r'D:\Desktop\code\6th-ABAW\EMI\ns.npy',allow_pickle=True).item()
data['preds']

In [3]:
128*300
128*32


4096

In [5]:
import torch

# 定义两个二维张量
tensor1 = torch.tensor([[1, 2, 3],
                        [4, 5, 6]])

tensor2 = torch.tensor([[7, 8, 9],
                        [10, 11, 12]])

# 将两个张量相加
sum_tensor = tensor1 + tensor2

# 求平均值
average_tensor = sum_tensor / 2

print("平均值张量:")
print(average_tensor)



平均值张量:
tensor([[4., 5., 6.],
        [7., 8., 9.]])


In [9]:
import torch

def decision_and_fusion(video_predictions, audio_predictions, video_weight=0.5, threshold=0.5):
    """
    视频和音频预测结果的融合函数
    
    参数：
    - video_predictions: 视频模态的预测结果，形状为 (batch_size, num_classes)
    - audio_predictions: 音频模态的预测结果，形状为 (batch_size, num_classes)
    - video_weight: 视频模态的权重，默认为0.5
    - threshold: 用于决策的阈值，默认为0.5
    
    返回值：
    - fusion: 融合后的最终预测结果，形状为 (batch_size, num_classes)
    """
    # 对视频和音频模态的预测结果进行加权平均
    fusion = video_weight * video_predictions + (1 - video_weight) * audio_predictions
    
    # 根据阈值进行决策
    fusion_decision = (fusion >= threshold).int()
    
    return fusion_decision

# 示例用法
video_predictions = torch.tensor([[0.8, 0.6, 0.4],
                                  [0.7, 0.5, 0.3]])

audio_predictions = torch.tensor([[0.6, 0.7, 0.5],
                                  [0.4, 0.6, 0.8]])

# fusion = decision_and_fusion(video_predictions, audio_predictions, video_weight=0.5, threshold=0.5)
# print("融合结果:")
# print(fusion)
c = torch.concat((video_predictions, audio_predictions), dim=1)
c.shape

torch.Size([2, 6])

In [5]:
import torch

def weighted_average_elementwise(tensor1, tensor2):
    # 计算权重之和
    total_weights = tensor1 + tensor2
    # 计算加权平均
    weighted_avg_tensor = (tensor1 * tensor1 + tensor2 * tensor2) / total_weights
    return weighted_avg_tensor

# 示例用法
tensor1 = torch.tensor([[5, 4],
                        [3, 2]])

tensor2 = torch.tensor([[1, 2],
                        [3, 4]])

result = weighted_average_elementwise(tensor1, tensor2)
print("加权平均:")
print(result)




加权平均:
tensor([[4.3333, 3.3333],
        [3.0000, 3.3333]])


In [2]:
import torch

# 假设 tensor 是你的二维张量
tensor = torch.tensor([[0.0, 0.0, 0.0],
                       [1.0, 2.0, 3.0],
                       [0.0, 0.0, 0.0],
                       [4.0, 5.0, 6.0]])

# 判断每一行是否全为零
nonzero_rows_mask = torch.any(tensor != 0, dim=1)


# 使用掩码来过滤非零行
nonzero_rows = tensor[nonzero_rows_mask]

print("去除全零行后的张量:")
print(nonzero_rows)


tensor([False,  True, False,  True])
去除全零行后的张量:
tensor([[1., 2., 3.],
        [4., 5., 6.]])
